"""segb_schemas.py — protobuf schemas for known Apple SEGB / Biome streams.

A *schema* tells the SEGB viewer how to decode a stream's protobuf records:
  - ``typedef``: a blackboxprotobuf typedef passed to ``decode_message`` so
    fields get the right types (timestamps as doubles, GUIDs as bytes, nested
    messages, etc.).
  - ``labels``: ``{field_path: name}`` (dotted paths for nesting, e.g. "4.3")
    giving each field a human name.
  - ``hints``: ``{field_path: "cocoa"|"unix"|"text"}`` for rendering values.

The built-in schemas below were ported from the iLEAPP ``biome*`` artifact
scripts (https://github.com/abrignoni/iLEAPP, MIT licensed) — all credit for the
field meanings and typedefs to that project and its contributors.  Users can
override or add schemas per case (stored in the case database); a user schema
takes precedence over a built-in one.
"""

import re


def stream_key_for_path(ui_path):
    """Return the Biome stream name from a path, e.g.
    '.../Biome/streams/restricted/_DKEvent.System.AirplaneMode/local/123'
    -> '_DKEvent.System.AirplaneMode'.  Returns None if not a Biome stream."""
    m = re.search(r"streams/(?:public|restricted)/([^/]+)/local", ui_path or "", re.I)
    return m.group(1) if m else None


def get_schema(stream_key):
    """Return the built-in schema dict for *stream_key*, or None."""
    return BUILTIN.get(stream_key)


BUILTIN = {'App.InFocus': {'hints': {'4': 'cocoa'},
                 'labels': {'3': 'Action', '4': 'Start Time', '6': 'Bundle ID'},
                 'typedef': {'10': {'name': '', 'type': 'str'},
                             '2': {'name': '', 'type': 'int'},
                             '3': {'name': '', 'type': 'int'},
                             '4': {'name': '', 'type': 'double'},
                             '6': {'name': '', 'type': 'str'},
                             '9': {'name': '', 'type': 'str'}}},
 'App.WebUsage': {'hints': {},
                  'labels': {},
                  'typedef': {'1': {'name': 'guid', 'type': 'str'},
                              '2': {'name': 'timestamp', 'type': 'double'},
                              '3': {'name': 'pb_int_3', 'type': 'int'},
                              '4': {'name': 'url', 'type': 'str'},
                              '5': {'name': 'domain', 'type': 'str'},
                              '6': {'name': 'bundle_id', 'type': 'str'},
                              '8': {'name': 'pb_int_8', 'type': 'int'}}},
 'Backlight': {'hints': {'1': 'cocoa'},
               'labels': {'1': 'Time Start', '2': 'State'},
               'typedef': {'1': {'name': '', 'type': 'double'}, '2': {'name': '', 'type': 'int'}}},
 'Device.Wireless.Bluetooth': {'hints': {'1': 'text', '2': 'text'},
                               'labels': {'1': 'MAC', '2': 'Name'},
                               'typedef': {}},
 'Device.Wireless.WiFi': {'hints': {},
                          'labels': {},
                          'typedef': {'1': {'name': 'SSID', 'type': 'str'},
                                      '2': {'name': 'Connect', 'type': 'int'}}},
 'NotesContent': {'hints': {'3': 'cocoa'},
                  'labels': {'1': 'Identifier 1',
                             '2': 'Identifier 2',
                             '3': 'Timestamp',
                             '5': 'Note'},
                  'typedef': {}},
 'Notification': {'hints': {'2': 'cocoa'},
                  'labels': {'14': 'Bundle ID', '2': 'Timestamp'},
                  'typedef': {'1': {'name': '', 'type': 'str'},
                              '11': {'name': '', 'type': 'int'},
                              '12': {'name': '', 'type': 'str'},
                              '14': {'name': '', 'type': 'str'},
                              '16': {'name': '', 'type': 'int'},
                              '2': {'name': '', 'type': 'double'},
                              '3': {'name': '', 'type': 'int'},
                              '4': {'name': '', 'type': 'str'},
                              '5': {'name': '', 'type': 'str'},
                              '8': {'name': '', 'type': 'str'},
                              '9': {'name': '', 'type': 'str'}}},
 'NowPlaying': {'hints': {'2': 'cocoa'},
                'labels': {'14.3': 'Output', '15': 'Bundle ID', '2': 'Timestamp'},
                'typedef': {'10': {'name': '', 'type': 'str'},
                            '13': {'name': '', 'type': 'int'},
                            '14': {'message_typedef': {'1': {'name': '', 'type': 'int'},
                                                       '2': {'name': '', 'type': 'int'},
                                                       '3': {'name': '', 'type': 'str'}},
                                   'name': '',
                                   'type': 'message'},
                            '15': {'name': '', 'type': 'str'},
                            '2': {'name': '', 'type': 'double'},
                            '3': {'name': '', 'type': 'int'},
                            '5': {'name': '', 'type': 'str'},
                            '6': {'name': '', 'type': 'int'},
                            '8': {'name': '', 'type': 'str'},
                            '9': {'name': '', 'type': 'int'}}},
 'OSAnalytics.Hardware.Reliability': {'hints': {},
                                      'labels': {'1': 'Hardware'},
                                      'typedef': {'1': {'name': '', 'type': 'str'}}},
 'TextInputSession': {'hints': {'2': 'cocoa'},
                      'labels': {'1': 'Duration', '2': 'Time Start'},
                      'typedef': {'1': {'name': '', 'type': 'double'},
                                  '2': {'name': '', 'type': 'double'},
                                  '3': {'name': '', 'type': 'str'},
                                  '4': {'name': '', 'type': 'int'}}},
 'UserActivityMetadata': {'hints': {'4': 'text', '5': 'text'},
                          'labels': {'2': 'Bplist Data', '4': 'Description', '5': 'Bundle ID'},
                          'typedef': {'1': {'message_typedef': {'1': {'name': '', 'type': 'str'},
                                                                '2': {'message_typedef': {'1': {'name': '',
                                                                                                'type': 'int'},
                                                                                          '2': {'name': '',
                                                                                                'type': 'int'}},
                                                                      'name': '',
                                                                      'type': 'message'}},
                                            'name': '',
                                            'type': 'message'},
                                      '10': {'name': '', 'type': 'int'},
                                      '2': {'name': '', 'type': 'double'},
                                      '3': {'name': '', 'type': 'double'},
                                      '4': {'message_typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                                                'type': 'int'},
                                                                                          '2': {'name': '',
                                                                                                'type': 'int'}},
                                                                      'name': '',
                                                                      'type': 'message'},
                                                                '5': {'name': '',
                                                                      'type': 'double'}},
                                            'name': '',
                                            'type': 'message'},
                                      '5': {'name': '', 'type': 'str'},
                                      '8': {'name': '', 'type': 'double'}}},
 '_DKEvent.App.InFocus': {'hints': {'2': 'cocoa', '3': 'cocoa', '8': 'cocoa'},
                          'labels': {'1.1': 'Activity',
                                     '2': 'Time Start',
                                     '3': 'Time End',
                                     '4.3': 'Bundle ID',
                                     '5': 'Action GUID',
                                     '8': 'Time Write'},
                          'typedef': {'1': {'message_typedef': {'1': {'name': '', 'type': 'str'},
                                                                '2': {'message_typedef': {'1': {'name': '',
                                                                                                'type': 'int'},
                                                                                          '2': {'name': '',
                                                                                                'type': 'int'}},
                                                                      'name': '',
                                                                      'type': 'message'}},
                                            'name': '',
                                            'type': 'message'},
                                      '10': {'name': '', 'type': 'int'},
                                      '2': {'name': '', 'type': 'double'},
                                      '3': {'name': '', 'type': 'double'},
                                      '4': {'message_typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                                                'type': 'int'},
                                                                                          '2': {'name': '',
                                                                                                'type': 'int'}},
                                                                      'name': '',
                                                                      'type': 'message'},
                                                                '3': {'name': '', 'type': 'str'}},
                                            'name': '',
                                            'type': 'message'},
                                      '5': {'name': '', 'type': 'str'},
                                      '7': {'message_typedef': {'1': {'message_typedef': {},
                                                                      'name': '',
                                                                      'type': 'message'},
                                                                '2': {'message_typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                                                                          'type': 'int'},
                                                                                                                    '2': {'name': '',
                                                                                                                          'type': 'int'}},
                                                                                                'name': '',
                                                                                                'type': 'message'},
                                                                                          '3': {'name': '',
                                                                                                'type': 'str'}},
                                                                      'name': '',
                                                                      'type': 'message'},
                                                                '3': {'name': '', 'type': 'int'}},
                                            'name': '',
                                            'type': 'message'},
                                      '8': {'name': '', 'type': 'double'}}},
 '_DKEvent.App.Install': {'hints': {'2': 'cocoa', '3': 'cocoa', '8': 'cocoa'},
                          'labels': {'1.1': 'Activity',
                                     '2': 'Time Start',
                                     '3': 'Time End',
                                     '4.3': 'Bundle ID',
                                     '5': 'Action GUID',
                                     '8': 'Time Write'},
                          'typedef': {'1': {'message_typedef': {'1': {'name': '', 'type': 'str'},
                                                                '2': {'message_typedef': {'1': {'name': '',
                                                                                                'type': 'int'},
                                                                                          '2': {'name': '',
                                                                                                'type': 'int'}},
                                                                      'name': '',
                                                                      'type': 'message'}},
                                            'name': '',
                                            'type': 'message'},
                                      '10': {'name': '', 'type': 'int'},
                                      '2': {'name': '', 'type': 'double'},
                                      '3': {'name': '', 'type': 'double'},
                                      '4': {'message_typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                                                'type': 'int'},
                                                                                          '2': {'name': '',
                                                                                                'type': 'int'}},
                                                                      'name': '',
                                                                      'type': 'message'},
                                                                '3': {'name': '', 'type': 'str'}},
                                            'name': '',
                                            'type': 'message'},
                                      '5': {'name': '', 'type': 'str'},
                                      '7': {'message_typedef': {'1': {'message_typedef': {},
                                                                      'name': '',
                                                                      'type': 'message'},
                                                                '2': {'message_typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                                                                          'type': 'int'},
                                                                                                                    '2': {'name': '',
                                                                                                                          'type': 'int'}},
                                                                                                'name': '',
                                                                                                'type': 'message'},
                                                                                          '3': {'name': '',
                                                                                                'type': 'str'},
                                                                                          '4': {'name': '',
                                                                                                'type': 'int'}},
                                                                      'name': '',
                                                                      'type': 'message'},
                                                                '3': {'name': '', 'type': 'int'}},
                                            'name': '',
                                            'type': 'message'},
                                      '8': {'name': '', 'type': 'double'}}},
 '_DKEvent.App.LocationActivity': {'hints': {'2': 'cocoa',
                                             '3': 'cocoa',
                                             '7.2.2.3': 'text',
                                             '7.4.2.3': 'text',
                                             '8': 'cocoa'},
                                   'labels': {'1.1': 'Activity',
                                              '2': 'Time Start',
                                              '3': 'Time End',
                                              '4.3': 'Bundle ID',
                                              '5': 'Action GUID',
                                              '6.1': 'Data 0',
                                              '6.2': 'Bundle ID 2',
                                              '8': 'Time Write'},
                                   'typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                               'type': 'str'},
                                                                         '2': {'message_typedef': {'1': {'name': '',
                                                                                                         'type': 'int'},
                                                                                                   '2': {'name': '',
                                                                                                         'type': 'int'}},
                                                                               'name': '',
                                                                               'type': 'message'}},
                                                     'name': '',
                                                     'type': 'message'},
                                               '10': {'name': '', 'type': 'int'},
                                               '2': {'name': '', 'type': 'double'},
                                               '3': {'name': '', 'type': 'double'},
                                               '4': {'message_typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                                                         'type': 'int'},
                                                                                                   '2': {'name': '',
                                                                                                         'type': 'int'}},
                                                                               'name': '',
                                                                               'type': 'message'},
                                                                         '3': {'name': '',
                                                                               'type': 'str'}},
                                                     'name': '',
                                                     'type': 'message'},
                                               '5': {'name': '', 'type': 'str'},
                                               '6': {'message_typedef': {'1': {'name': '',
                                                                               'type': 'str'},
                                                                         '2': {'name': '',
                                                                               'type': 'str'},
                                                                         '3': {'name': '',
                                                                               'type': 'bytes'},
                                                                         '6': {'name': '',
                                                                               'type': 'int'}},
                                                     'name': '',
                                                     'type': 'message'},
                                               '7': {'message_typedef': {'1': {'message_typedef': {},
                                                                               'name': '',
                                                                               'type': 'message'},
                                                                         '2': {'message_typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                                                                                   'type': 'int'},
                                                                                                                             '2': {'name': '',
                                                                                                                                   'type': 'int'}},
                                                                                                         'name': '',
                                                                                                         'type': 'message'},
                                                                                                   '3': {'name': '',
                                                                                                         'type': 'bytes'},
                                                                                                   '4': {'name': '',
                                                                                                         'type': 'int'},
                                                                                                   '5': {'name': '',
                                                                                                         'type': 'fixed64'},
                                                                                                   '6': {'name': '',
                                                                                                         'type': 'bytes'},
                                                                                                   '7': {'name': '',
                                                                                                         'type': 'fixed64'}},
                                                                               'name': '',
                                                                               'type': 'message'},
                                                                         '3': {'name': '',
                                                                               'type': 'int'}},
                                                     'name': '',
                                                     'type': 'message'},
                                               '8': {'name': '', 'type': 'double'}}},
 '_DKEvent.Carplay.IsConnected': {'hints': {'2': 'cocoa', '3': 'cocoa', '8': 'cocoa'},
                                  'labels': {'1.1': 'Activity',
                                             '2': 'Time Start',
                                             '3': 'Time End',
                                             '4.4': 'Status',
                                             '5': 'Action GUID',
                                             '8': 'Time Write'},
                                  'typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                              'type': 'str'},
                                                                        '2': {'message_typedef': {'1': {'name': '',
                                                                                                        'type': 'int'},
                                                                                                  '2': {'name': '',
                                                                                                        'type': 'int'}},
                                                                              'name': '',
                                                                              'type': 'message'}},
                                                    'name': '',
                                                    'type': 'message'},
                                              '10': {'name': '', 'type': 'int'},
                                              '2': {'name': '', 'type': 'double'},
                                              '3': {'name': '', 'type': 'double'},
                                              '4': {'message_typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                                                        'type': 'int'},
                                                                                                  '2': {'name': '',
                                                                                                        'type': 'int'}},
                                                                              'name': '',
                                                                              'type': 'message'},
                                                                        '4': {'name': '',
                                                                              'type': 'int'}},
                                                    'name': '',
                                                    'type': 'message'},
                                              '5': {'name': '', 'type': 'str'},
                                              '8': {'name': '', 'type': 'double'}}},
 '_DKEvent.Device.BatteryPercentage': {'hints': {'2': 'cocoa', '3': 'cocoa', '8': 'cocoa'},
                                       'labels': {'1.1': 'Activity',
                                                  '2': 'Time Start',
                                                  '3': 'Time End',
                                                  '4.5': 'Battery %',
                                                  '5': 'Action GUID',
                                                  '8': 'Time Write'},
                                       'typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                                   'type': 'str'},
                                                                             '2': {'message_typedef': {'1': {'name': '',
                                                                                                             'type': 'int'},
                                                                                                       '2': {'name': '',
                                                                                                             'type': 'int'}},
                                                                                   'name': '',
                                                                                   'type': 'message'}},
                                                         'name': '',
                                                         'type': 'message'},
                                                   '10': {'name': '', 'type': 'int'},
                                                   '2': {'name': '', 'type': 'double'},
                                                   '3': {'name': '', 'type': 'double'},
                                                   '4': {'message_typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                                                             'type': 'int'},
                                                                                                       '2': {'name': '',
                                                                                                             'type': 'int'}},
                                                                                   'name': '',
                                                                                   'type': 'message'},
                                                                             '5': {'name': '',
                                                                                   'type': 'double'}},
                                                         'name': '',
                                                         'type': 'message'},
                                                   '5': {'name': '', 'type': 'str'},
                                                   '8': {'name': '', 'type': 'double'}}},
 '_DKEvent.Device.IsPluggedIn': {'hints': {'2': 'cocoa', '3': 'cocoa', '8': 'cocoa'},
                                 'labels': {'1.1': 'Activity',
                                            '2': 'Time Start',
                                            '3': 'Time End',
                                            '4.4': 'Status',
                                            '5': 'Action GUID',
                                            '8': 'Time Write'},
                                 'typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                             'type': 'str'},
                                                                       '2': {'message_typedef': {'1': {'name': '',
                                                                                                       'type': 'int'},
                                                                                                 '2': {'name': '',
                                                                                                       'type': 'int'}},
                                                                             'name': '',
                                                                             'type': 'message'}},
                                                   'name': '',
                                                   'type': 'message'},
                                             '10': {'name': '', 'type': 'int'},
                                             '2': {'name': '', 'type': 'double'},
                                             '3': {'name': '', 'type': 'double'},
                                             '4': {'message_typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                                                       'type': 'int'},
                                                                                                 '2': {'name': '',
                                                                                                       'type': 'int'}},
                                                                             'name': '',
                                                                             'type': 'message'},
                                                                       '4': {'name': '',
                                                                             'type': 'int'}},
                                                   'name': '',
                                                   'type': 'message'},
                                             '5': {'name': '', 'type': 'str'},
                                             '7': {'message_typedef': {'1': {'message_typedef': {},
                                                                             'name': '',
                                                                             'type': 'message'},
                                                                       '2': {'message_typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                                                                                 'type': 'int'},
                                                                                                                           '2': {'name': '',
                                                                                                                                 'type': 'int'}},
                                                                                                       'name': '',
                                                                                                       'type': 'message'},
                                                                                                 '4': {'name': '',
                                                                                                       'type': 'int'}},
                                                                             'name': '',
                                                                             'type': 'message'},
                                                                       '3': {'name': '',
                                                                             'type': 'int'}},
                                                   'name': '',
                                                   'type': 'message'},
                                             '8': {'name': '', 'type': 'double'}}},
 '_DKEvent.Keybag.IsLocked': {'hints': {'2': 'cocoa', '3': 'cocoa'},
                              'labels': {'2': 'Start Time', '3': 'End Time'},
                              'typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                          'type': 'str'},
                                                                    '2': {'message_typedef': {'1': {'name': '',
                                                                                                    'type': 'int'},
                                                                                              '2': {'name': '',
                                                                                                    'type': 'int'}},
                                                                          'name': '',
                                                                          'type': 'message'}},
                                                'name': '',
                                                'type': 'message'},
                                          '10': {'name': '', 'type': 'int'},
                                          '2': {'name': '', 'type': 'double'},
                                          '3': {'name': '', 'type': 'double'},
                                          '4': {'message_typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                                                    'type': 'int'},
                                                                                              '2': {'name': '',
                                                                                                    'type': 'int'}},
                                                                          'name': '',
                                                                          'type': 'message'},
                                                                    '4': {'name': '',
                                                                          'type': 'int'}},
                                                'name': '',
                                                'type': 'message'},
                                          '5': {'name': '', 'type': 'bytes'},
                                          '8': {'name': '', 'type': 'double'}}},
 '_DKEvent.Safari.History': {'hints': {'2': 'cocoa'},
                             'labels': {'1.1': 'Activity',
                                        '2': 'Timestamp',
                                        '4.3': 'URL',
                                        '5': 'GUID',
                                        '6.1': 'Detail',
                                        '6.2': 'Detail 2',
                                        '6.4': 'Detail 3',
                                        '7.2.3': 'Title'},
                             'typedef': {'1': {'message_typedef': {'1': {'name': '', 'type': 'str'},
                                                                   '2': {'message_typedef': {'1': {'name': '',
                                                                                                   'type': 'int'},
                                                                                             '2': {'name': '',
                                                                                                   'type': 'int'}},
                                                                         'name': '',
                                                                         'type': 'message'}},
                                               'name': '',
                                               'type': 'message'},
                                         '10': {'name': '', 'type': 'int'},
                                         '2': {'name': '', 'type': 'double'},
                                         '3': {'name': '', 'type': 'double'},
                                         '4': {'message_typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                                                   'type': 'int'},
                                                                                             '2': {'name': '',
                                                                                                   'type': 'int'}},
                                                                         'name': '',
                                                                         'type': 'message'},
                                                                   '3': {'name': '',
                                                                         'type': 'str'}},
                                               'name': '',
                                               'type': 'message'},
                                         '5': {'name': '', 'type': 'str'},
                                         '6': {'message_typedef': {'1': {'name': '', 'type': 'str'},
                                                                   '2': {'name': '', 'type': 'str'},
                                                                   '3': {'name': '', 'type': 'str'},
                                                                   '4': {'name': '', 'type': 'str'},
                                                                   '6': {'name': '',
                                                                         'type': 'int'}},
                                               'name': '',
                                               'type': 'message'},
                                         '7': {'message_typedef': {'1': {'message_typedef': {},
                                                                         'name': '',
                                                                         'type': 'message'},
                                                                   '2': {'message_typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                                                                             'type': 'int'},
                                                                                                                       '2': {'name': '',
                                                                                                                             'type': 'int'}},
                                                                                                   'name': '',
                                                                                                   'type': 'message'},
                                                                                             '3': {'name': '',
                                                                                                   'type': 'str'}},
                                                                         'name': '',
                                                                         'type': 'message'},
                                                                   '3': {'name': '',
                                                                         'type': 'int'}},
                                               'name': '',
                                               'type': 'message'},
                                         '8': {'name': '', 'type': 'fixed64'}}},
 '_DKEvent.System.AirplaneMode': {'hints': {'2': 'cocoa', '3': 'cocoa', '5': 'text'},
                                  'labels': {'1.1': 'Event',
                                             '2': 'Time Start',
                                             '3': 'Time End',
                                             '5': 'GUID'},
                                  'typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                              'type': 'str'},
                                                                        '2': {'message_typedef': {'1': {'name': '',
                                                                                                        'type': 'int'},
                                                                                                  '2': {'name': '',
                                                                                                        'type': 'int'}},
                                                                              'name': '',
                                                                              'type': 'message'}},
                                                    'name': '',
                                                    'type': 'message'},
                                              '10': {'name': '', 'type': 'int'},
                                              '2': {'name': '', 'type': 'double'},
                                              '3': {'name': '', 'type': 'double'},
                                              '4': {'message_typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                                                        'type': 'int'},
                                                                                                  '2': {'name': '',
                                                                                                        'type': 'int'}},
                                                                              'name': '',
                                                                              'type': 'message'},
                                                                        '3': {'message_typedef': {'8': {'name': '',
                                                                                                        'type': 'fixed64'}},
                                                                              'name': '',
                                                                              'type': 'bytes'}},
                                                    'name': '',
                                                    'type': 'message'},
                                              '5': {'name': '', 'type': 'bytes'},
                                              '8': {'name': '', 'type': 'fixed64'}}},
 '_DKEvent.Wifi.Connection': {'hints': {'2': 'cocoa', '5': 'text'},
                              'labels': {'1.1': 'Event',
                                         '2': 'Timestamp',
                                         '4.3': 'Device',
                                         '5': 'GUID'},
                              'typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                          'type': 'str'},
                                                                    '2': {'message_typedef': {'1': {'name': '',
                                                                                                    'type': 'int'},
                                                                                              '2': {'name': '',
                                                                                                    'type': 'int'}},
                                                                          'name': '',
                                                                          'type': 'message'}},
                                                'name': '',
                                                'type': 'message'},
                                          '10': {'name': '', 'type': 'int'},
                                          '2': {'name': '', 'type': 'double'},
                                          '3': {'name': '', 'type': 'double'},
                                          '4': {'message_typedef': {'1': {'message_typedef': {'1': {'name': '',
                                                                                                    'type': 'int'},
                                                                                              '2': {'name': '',
                                                                                                    'type': 'int'}},
                                                                          'name': '',
                                                                          'type': 'message'},
                                                                    '3': {'message_typedef': {'8': {'name': '',
                                                                                                    'type': 'fixed64'}},
                                                                          'name': '',
                                                                          'type': 'bytes'}},
                                                'name': '',
                                                'type': 'message'},
                                          '5': {'name': '', 'type': 'bytes'},
                                          '8': {'name': '', 'type': 'fixed64'}}}}
